### ISSUE TITLE
Code error 

### ISSUE THREAD

**Issue by dt-ahmed-touila** [lethienhoa/Very-Deep-Convolutional-Networks-for-Natural-Language-Processing#2]
Hi, thank you for your work. 
You have a code error in the model.py script on line 29 :
`b = tf.Variable(tf.constant(0.1, shape=[num_filters_per_size]), name="b")`
Wrong shape it should be : 
`b = tf.Variable(tf.constant(0.1, shape=[num_filters_per_size[0]]), name="b")`

**Comment by lethienhoa** [comment]
Great, thanks @Touila !
